// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddCleanupTask(arg1) {
  return window['go']['main']['App']['AddCleanupTask'](arg1);
}

export function AddClipboardItem(arg1, arg2) {
  return window['go']['main']['App']['AddClipboardItem'](arg1, arg2);
}

export function AddToPathVariable(arg1, arg2) {
  return window['go']['main']['App']['AddToPathVariable'](arg1, arg2);
}

export function AddWatermarkToImages(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AddWatermarkToImages'](arg1, arg2, arg3, arg4);
}

export function AnalyzeFolderSizes(arg1, arg2) {
  return window['go']['main']['App']['AnalyzeFolderSizes'](arg1, arg2);
}

export function AnalyzeServiceImpact(arg1) {
  return window['go']['main']['App']['AnalyzeServiceImpact'](arg1);
}

export function ApplyOptimizationProfile(arg1) {
  return window['go']['main']['App']['ApplyOptimizationProfile'](arg1);
}

export function Base32ToHex(arg1) {
  return window['go']['main']['App']['Base32ToHex'](arg1);
}

export function BatchCompressImages(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['BatchCompressImages'](arg1, arg2, arg3, arg4);
}

export function BatchKillProcesses(arg1) {
  return window['go']['main']['App']['BatchKillProcesses'](arg1);
}

export function BatchPing(arg1, arg2) {
  return window['go']['main']['App']['BatchPing'](arg1, arg2);
}

export function BatchUninstallSoftware(arg1) {
  return window['go']['main']['App']['BatchUninstallSoftware'](arg1);
}

export function BeautifyCSS(arg1) {
  return window['go']['main']['App']['BeautifyCSS'](arg1);
}

export function BeautifyHTML(arg1) {
  return window['go']['main']['App']['BeautifyHTML'](arg1);
}

export function BeautifySQL(arg1) {
  return window['go']['main']['App']['BeautifySQL'](arg1);
}

export function BlockPort(arg1, arg2, arg3) {
  return window['go']['main']['App']['BlockPort'](arg1, arg2, arg3);
}

export function BlockProgram(arg1, arg2) {
  return window['go']['main']['App']['BlockProgram'](arg1, arg2);
}

export function Calculate(arg1) {
  return window['go']['main']['App']['Calculate'](arg1);
}

export function CanDisableService(arg1) {
  return window['go']['main']['App']['CanDisableService'](arg1);
}

export function CaptureAllScreens() {
  return window['go']['main']['App']['CaptureAllScreens']();
}

export function CaptureScreen(arg1) {
  return window['go']['main']['App']['CaptureScreen'](arg1);
}

export function ChangeService(arg1, arg2) {
  return window['go']['main']['App']['ChangeService'](arg1, arg2);
}

export function CheckContextMenu() {
  return window['go']['main']['App']['CheckContextMenu']();
}

export function CheckDiskErrors(arg1) {
  return window['go']['main']['App']['CheckDiskErrors'](arg1);
}

export function CheckIPConflict(arg1) {
  return window['go']['main']['App']['CheckIPConflict'](arg1);
}

export function CheckToolExists(arg1) {
  return window['go']['main']['App']['CheckToolExists'](arg1);
}

export function CheckUpdate(arg1) {
  return window['go']['main']['App']['CheckUpdate'](arg1);
}

export function CleanBrowserData(arg1) {
  return window['go']['main']['App']['CleanBrowserData'](arg1);
}

export function CleanTargets(arg1) {
  return window['go']['main']['App']['CleanTargets'](arg1);
}

export function ClearClipboardHistory() {
  return window['go']['main']['App']['ClearClipboardHistory']();
}

export function ClearFolderMonitorEvents() {
  return window['go']['main']['App']['ClearFolderMonitorEvents']();
}

export function ClearOperationLogs() {
  return window['go']['main']['App']['ClearOperationLogs']();
}

export function ClearPerfHistory() {
  return window['go']['main']['App']['ClearPerfHistory']();
}

export function ClearRecentDocs() {
  return window['go']['main']['App']['ClearRecentDocs']();
}

export function ClearServiceBackups() {
  return window['go']['main']['App']['ClearServiceBackups']();
}

export function ComputeFileHash(arg1, arg2) {
  return window['go']['main']['App']['ComputeFileHash'](arg1, arg2);
}

export function ConvertColor(arg1) {
  return window['go']['main']['App']['ConvertColor'](arg1);
}

export function ConvertCurrency(arg1, arg2, arg3) {
  return window['go']['main']['App']['ConvertCurrency'](arg1, arg2, arg3);
}

export function ConvertEncoding(arg1, arg2, arg3) {
  return window['go']['main']['App']['ConvertEncoding'](arg1, arg2, arg3);
}

export function ConvertImage(arg1, arg2) {
  return window['go']['main']['App']['ConvertImage'](arg1, arg2);
}

export function ConvertTimestamp(arg1, arg2) {
  return window['go']['main']['App']['ConvertTimestamp'](arg1, arg2);
}

export function ConvertToPDF(arg1) {
  return window['go']['main']['App']['ConvertToPDF'](arg1);
}

export function CreateRestorePoint(arg1) {
  return window['go']['main']['App']['CreateRestorePoint'](arg1);
}

export function CreateScheduledTask(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateScheduledTask'](arg1, arg2, arg3);
}

export function DNSLookup(arg1) {
  return window['go']['main']['App']['DNSLookup'](arg1);
}

export function DateToTimestamp(arg1) {
  return window['go']['main']['App']['DateToTimestamp'](arg1);
}

export function DecodeBase64(arg1) {
  return window['go']['main']['App']['DecodeBase64'](arg1);
}

export function DecodeJWT(arg1) {
  return window['go']['main']['App']['DecodeJWT'](arg1);
}

export function DecodeURL(arg1) {
  return window['go']['main']['App']['DecodeURL'](arg1);
}

export function DecryptFile(arg1, arg2) {
  return window['go']['main']['App']['DecryptFile'](arg1, arg2);
}

export function DeleteCleanupTask(arg1) {
  return window['go']['main']['App']['DeleteCleanupTask'](arg1);
}

export function DeleteEnvironmentVariable(arg1, arg2) {
  return window['go']['main']['App']['DeleteEnvironmentVariable'](arg1, arg2);
}

export function DeleteFirewallRule(arg1) {
  return window['go']['main']['App']['DeleteFirewallRule'](arg1);
}

export function DeleteScheduledTask(arg1) {
  return window['go']['main']['App']['DeleteScheduledTask'](arg1);
}

export function DeleteStartupProgram(arg1, arg2) {
  return window['go']['main']['App']['DeleteStartupProgram'](arg1, arg2);
}

export function DetectBrowsers() {
  return window['go']['main']['App']['DetectBrowsers']();
}

export function DiagnoseNetwork() {
  return window['go']['main']['App']['DiagnoseNetwork']();
}

export function DiffFiles(arg1, arg2) {
  return window['go']['main']['App']['DiffFiles'](arg1, arg2);
}

export function DiffText(arg1, arg2) {
  return window['go']['main']['App']['DiffText'](arg1, arg2);
}

export function DisableBrowserExtension(arg1, arg2) {
  return window['go']['main']['App']['DisableBrowserExtension'](arg1, arg2);
}

export function EnableBrowserExtension(arg1, arg2) {
  return window['go']['main']['App']['EnableBrowserExtension'](arg1, arg2);
}

export function EncodeBase64(arg1) {
  return window['go']['main']['App']['EncodeBase64'](arg1);
}

export function EncodeURL(arg1) {
  return window['go']['main']['App']['EncodeURL'](arg1);
}

export function EncryptFile(arg1, arg2) {
  return window['go']['main']['App']['EncryptFile'](arg1, arg2);
}

export function ExportSoftwareList(arg1, arg2) {
  return window['go']['main']['App']['ExportSoftwareList'](arg1, arg2);
}

export function FindDuplicateFiles(arg1, arg2) {
  return window['go']['main']['App']['FindDuplicateFiles'](arg1, arg2);
}

export function FindLargeFiles(arg1, arg2, arg3) {
  return window['go']['main']['App']['FindLargeFiles'](arg1, arg2, arg3);
}

export function FixAllNetwork() {
  return window['go']['main']['App']['FixAllNetwork']();
}

export function FixRegistryItems(arg1) {
  return window['go']['main']['App']['FixRegistryItems'](arg1);
}

export function FlushDNSCache() {
  return window['go']['main']['App']['FlushDNSCache']();
}

export function FormatJSON(arg1) {
  return window['go']['main']['App']['FormatJSON'](arg1);
}

export function FormatTOML(arg1) {
  return window['go']['main']['App']['FormatTOML'](arg1);
}

export function FormatYAML(arg1) {
  return window['go']['main']['App']['FormatYAML'](arg1);
}

export function GeneratePassword(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['GeneratePassword'](arg1, arg2, arg3, arg4, arg5);
}

export function GenerateQRCode(arg1, arg2) {
  return window['go']['main']['App']['GenerateQRCode'](arg1, arg2);
}

export function GenerateSystemReport(arg1) {
  return window['go']['main']['App']['GenerateSystemReport'](arg1);
}

export function GenerateUUID() {
  return window['go']['main']['App']['GenerateUUID']();
}

export function GenerateUUIDs(arg1, arg2) {
  return window['go']['main']['App']['GenerateUUIDs'](arg1, arg2);
}

export function GetActivationInfo() {
  return window['go']['main']['App']['GetActivationInfo']();
}

export function GetActivationTools() {
  return window['go']['main']['App']['GetActivationTools']();
}

export function GetAllNetConnections() {
  return window['go']['main']['App']['GetAllNetConnections']();
}

export function GetAllStartupPrograms() {
  return window['go']['main']['App']['GetAllStartupPrograms']();
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetBatteryInfo() {
  return window['go']['main']['App']['GetBatteryInfo']();
}

export function GetBrowserExtensions() {
  return window['go']['main']['App']['GetBrowserExtensions']();
}

export function GetBuildDate() {
  return window['go']['main']['App']['GetBuildDate']();
}

export function GetCleanupLogs(arg1) {
  return window['go']['main']['App']['GetCleanupLogs'](arg1);
}

export function GetCleanupStats() {
  return window['go']['main']['App']['GetCleanupStats']();
}

export function GetCleanupTasks() {
  return window['go']['main']['App']['GetCleanupTasks']();
}

export function GetClipboardAndTranslate(arg1) {
  return window['go']['main']['App']['GetClipboardAndTranslate'](arg1);
}

export function GetClipboardHistory() {
  return window['go']['main']['App']['GetClipboardHistory']();
}

export function GetClipboardText() {
  return window['go']['main']['App']['GetClipboardText']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetDiskHealthInfo() {
  return window['go']['main']['App']['GetDiskHealthInfo']();
}

export function GetDiskSpaceInfo() {
  return window['go']['main']['App']['GetDiskSpaceInfo']();
}

export function GetEnvironmentVariables(arg1) {
  return window['go']['main']['App']['GetEnvironmentVariables'](arg1);
}

export function GetEstablishedConnections() {
  return window['go']['main']['App']['GetEstablishedConnections']();
}

export function GetExchangeRate(arg1, arg2) {
  return window['go']['main']['App']['GetExchangeRate'](arg1, arg2);
}

export function GetExternalTools() {
  return window['go']['main']['App']['GetExternalTools']();
}

export function GetFileAssociations() {
  return window['go']['main']['App']['GetFileAssociations']();
}

export function GetFirewallRules(arg1) {
  return window['go']['main']['App']['GetFirewallRules'](arg1);
}

export function GetFirewallStatus() {
  return window['go']['main']['App']['GetFirewallStatus']();
}

export function GetFolderMonitorEvents() {
  return window['go']['main']['App']['GetFolderMonitorEvents']();
}

export function GetHardwareMonitor() {
  return window['go']['main']['App']['GetHardwareMonitor']();
}

export function GetHostsEntries() {
  return window['go']['main']['App']['GetHostsEntries']();
}

export function GetInstalledSoftware() {
  return window['go']['main']['App']['GetInstalledSoftware']();
}

export function GetKMSMethods() {
  return window['go']['main']['App']['GetKMSMethods']();
}

export function GetListeningConnections() {
  return window['go']['main']['App']['GetListeningConnections']();
}

export function GetNetConnectionStats() {
  return window['go']['main']['App']['GetNetConnectionStats']();
}

export function GetNetworkConnections() {
  return window['go']['main']['App']['GetNetworkConnections']();
}

export function GetNowTimestamp() {
  return window['go']['main']['App']['GetNowTimestamp']();
}

export function GetOpenWithList(arg1) {
  return window['go']['main']['App']['GetOpenWithList'](arg1);
}

export function GetOperationLogs() {
  return window['go']['main']['App']['GetOperationLogs']();
}

export function GetOptimizationProfiles() {
  return window['go']['main']['App']['GetOptimizationProfiles']();
}

export function GetPathVariable(arg1) {
  return window['go']['main']['App']['GetPathVariable'](arg1);
}

export function GetPendingUpdates() {
  return window['go']['main']['App']['GetPendingUpdates']();
}

export function GetPerfHistory() {
  return window['go']['main']['App']['GetPerfHistory']();
}

export function GetPerfSnapshot() {
  return window['go']['main']['App']['GetPerfSnapshot']();
}

export function GetPowerPlans() {
  return window['go']['main']['App']['GetPowerPlans']();
}

export function GetProcessList() {
  return window['go']['main']['App']['GetProcessList']();
}

export function GetRestorePoints() {
  return window['go']['main']['App']['GetRestorePoints']();
}

export function GetServiceBackups() {
  return window['go']['main']['App']['GetServiceBackups']();
}

export function GetServiceDependencyGraph() {
  return window['go']['main']['App']['GetServiceDependencyGraph']();
}

export function GetServices() {
  return window['go']['main']['App']['GetServices']();
}

export function GetShortcutKeys() {
  return window['go']['main']['App']['GetShortcutKeys']();
}

export function GetStartupItemDelay(arg1) {
  return window['go']['main']['App']['GetStartupItemDelay'](arg1);
}

export function GetStartupItems() {
  return window['go']['main']['App']['GetStartupItems']();
}

export function GetSupportedCurrencies() {
  return window['go']['main']['App']['GetSupportedCurrencies']();
}

export function GetSystemInfo() {
  return window['go']['main']['App']['GetSystemInfo']();
}

export function GetTemperatures() {
  return window['go']['main']['App']['GetTemperatures']();
}

export function GetToolsDir() {
  return window['go']['main']['App']['GetToolsDir']();
}

export function GetTrafficSamples(arg1) {
  return window['go']['main']['App']['GetTrafficSamples'](arg1);
}

export function GetWiFiPasswords() {
  return window['go']['main']['App']['GetWiFiPasswords']();
}

export function GetWindowsUpdates() {
  return window['go']['main']['App']['GetWindowsUpdates']();
}

export function HSLToColor(arg1, arg2, arg3) {
  return window['go']['main']['App']['HSLToColor'](arg1, arg2, arg3);
}

export function HasBattery() {
  return window['go']['main']['App']['HasBattery']();
}

export function HexToBase32(arg1) {
  return window['go']['main']['App']['HexToBase32'](arg1);
}

export function HexToColor(arg1) {
  return window['go']['main']['App']['HexToColor'](arg1);
}

export function InstallContextMenu() {
  return window['go']['main']['App']['InstallContextMenu']();
}

export function InstallContextMenuDir() {
  return window['go']['main']['App']['InstallContextMenuDir']();
}

export function IsFolderMonitoring() {
  return window['go']['main']['App']['IsFolderMonitoring']();
}

export function IsRecording() {
  return window['go']['main']['App']['IsRecording']();
}

export function KillNetConnection(arg1) {
  return window['go']['main']['App']['KillNetConnection'](arg1);
}

export function KillProcess(arg1) {
  return window['go']['main']['App']['KillProcess'](arg1);
}

export function LaunchMSTSC(arg1, arg2, arg3) {
  return window['go']['main']['App']['LaunchMSTSC'](arg1, arg2, arg3);
}

export function ListScheduledTasks() {
  return window['go']['main']['App']['ListScheduledTasks']();
}

export function MenuQuit() {
  return window['go']['main']['App']['MenuQuit']();
}

export function MenuShowApp() {
  return window['go']['main']['App']['MenuShowApp']();
}

export function MinifyJSON(arg1) {
  return window['go']['main']['App']['MinifyJSON'](arg1);
}

export function OpenDirectory(arg1) {
  return window['go']['main']['App']['OpenDirectory'](arg1);
}

export function OpenExternalURL(arg1) {
  return window['go']['main']['App']['OpenExternalURL'](arg1);
}

export function OpenInExplorer(arg1) {
  return window['go']['main']['App']['OpenInExplorer'](arg1);
}

export function OptimizeDrive(arg1) {
  return window['go']['main']['App']['OptimizeDrive'](arg1);
}

export function Ping(arg1, arg2, arg3) {
  return window['go']['main']['App']['Ping'](arg1, arg2, arg3);
}

export function PortScan(arg1, arg2) {
  return window['go']['main']['App']['PortScan'](arg1, arg2);
}

export function PreviewFile(arg1) {
  return window['go']['main']['App']['PreviewFile'](arg1);
}

export function QueryGeoIP(arg1) {
  return window['go']['main']['App']['QueryGeoIP'](arg1);
}

export function RGBToColor(arg1, arg2, arg3) {
  return window['go']['main']['App']['RGBToColor'](arg1, arg2, arg3);
}

export function ReadClipboardImage() {
  return window['go']['main']['App']['ReadClipboardImage']();
}

export function ReadFileAsBase64(arg1) {
  return window['go']['main']['App']['ReadFileAsBase64'](arg1);
}

export function ReleaseIP() {
  return window['go']['main']['App']['ReleaseIP']();
}

export function RemoveBrowserExtension(arg1, arg2) {
  return window['go']['main']['App']['RemoveBrowserExtension'](arg1, arg2);
}

export function RemoveClipboardItem(arg1) {
  return window['go']['main']['App']['RemoveClipboardItem'](arg1);
}

export function RemoveFileAssociation(arg1) {
  return window['go']['main']['App']['RemoveFileAssociation'](arg1);
}

export function RemoveFromPathVariable(arg1, arg2) {
  return window['go']['main']['App']['RemoveFromPathVariable'](arg1, arg2);
}

export function RenewIP() {
  return window['go']['main']['App']['RenewIP']();
}

export function ResetArpCache() {
  return window['go']['main']['App']['ResetArpCache']();
}

export function ResetProxy() {
  return window['go']['main']['App']['ResetProxy']();
}

export function ResetTCPIP() {
  return window['go']['main']['App']['ResetTCPIP']();
}

export function ResetWinsock() {
  return window['go']['main']['App']['ResetWinsock']();
}

export function RestoreService(arg1) {
  return window['go']['main']['App']['RestoreService'](arg1);
}

export function RunCleanupTask(arg1) {
  return window['go']['main']['App']['RunCleanupTask'](arg1);
}

export function RunExternalTool(arg1) {
  return window['go']['main']['App']['RunExternalTool'](arg1);
}

export function RunHealthCheck() {
  return window['go']['main']['App']['RunHealthCheck']();
}

export function SaveClipboardImage(arg1) {
  return window['go']['main']['App']['SaveClipboardImage'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SaveHostsEntries(arg1) {
  return window['go']['main']['App']['SaveHostsEntries'](arg1);
}

export function ScanBrowserData() {
  return window['go']['main']['App']['ScanBrowserData']();
}

export function ScanCleanupPaths() {
  return window['go']['main']['App']['ScanCleanupPaths']();
}

export function ScanDiskTree(arg1, arg2) {
  return window['go']['main']['App']['ScanDiskTree'](arg1, arg2);
}

export function ScanLAN() {
  return window['go']['main']['App']['ScanLAN']();
}

export function ScanRegistry() {
  return window['go']['main']['App']['ScanRegistry']();
}

export function ScanWiFiSignal() {
  return window['go']['main']['App']['ScanWiFiSignal']();
}

export function SearchAndReplace(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SearchAndReplace'](arg1, arg2, arg3, arg4);
}

export function SearchFileContent(arg1, arg2, arg3) {
  return window['go']['main']['App']['SearchFileContent'](arg1, arg2, arg3);
}

export function SearchNetConnections(arg1) {
  return window['go']['main']['App']['SearchNetConnections'](arg1);
}

export function SearchStartupPrograms(arg1) {
  return window['go']['main']['App']['SearchStartupPrograms'](arg1);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SelectFile() {
  return window['go']['main']['App']['SelectFile']();
}

export function SendHTTPRequest(arg1) {
  return window['go']['main']['App']['SendHTTPRequest'](arg1);
}

export function SetEnvironmentVariable(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetEnvironmentVariable'](arg1, arg2, arg3);
}

export function SetFileAssociation(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetFileAssociation'](arg1, arg2, arg3);
}

export function SetPowerPlan(arg1) {
  return window['go']['main']['App']['SetPowerPlan'](arg1);
}

export function SetProcessPriority(arg1, arg2) {
  return window['go']['main']['App']['SetProcessPriority'](arg1, arg2);
}

export function SetStartupItemDelay(arg1, arg2) {
  return window['go']['main']['App']['SetStartupItemDelay'](arg1, arg2);
}

export function ShredDir(arg1, arg2) {
  return window['go']['main']['App']['ShredDir'](arg1, arg2);
}

export function ShredFile(arg1, arg2) {
  return window['go']['main']['App']['ShredFile'](arg1, arg2);
}

export function StartFolderMonitor(arg1) {
  return window['go']['main']['App']['StartFolderMonitor'](arg1);
}

export function StartScreenRecording(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartScreenRecording'](arg1, arg2, arg3);
}

export function StopFolderMonitor() {
  return window['go']['main']['App']['StopFolderMonitor']();
}

export function StopScreenRecording() {
  return window['go']['main']['App']['StopScreenRecording']();
}

export function TestRegex(arg1, arg2) {
  return window['go']['main']['App']['TestRegex'](arg1, arg2);
}

export function TimestampToDate(arg1) {
  return window['go']['main']['App']['TimestampToDate'](arg1);
}

export function ToggleCleanupTask(arg1, arg2) {
  return window['go']['main']['App']['ToggleCleanupTask'](arg1, arg2);
}

export function ToggleFirewallRule(arg1, arg2) {
  return window['go']['main']['App']['ToggleFirewallRule'](arg1, arg2);
}

export function ToggleStartupItem(arg1, arg2) {
  return window['go']['main']['App']['ToggleStartupItem'](arg1, arg2);
}

export function ToggleStartupProgram(arg1, arg2, arg3) {
  return window['go']['main']['App']['ToggleStartupProgram'](arg1, arg2, arg3);
}

export function Translate(arg1, arg2, arg3) {
  return window['go']['main']['App']['Translate'](arg1, arg2, arg3);
}

export function UninstallContextMenu() {
  return window['go']['main']['App']['UninstallContextMenu']();
}

export function UninstallSoftware(arg1) {
  return window['go']['main']['App']['UninstallSoftware'](arg1);
}

export function UpdateCleanupTask(arg1) {
  return window['go']['main']['App']['UpdateCleanupTask'](arg1);
}

export function UploadFileToServer(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UploadFileToServer'](arg1, arg2, arg3, arg4);
}
