// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {optimize} from '../models';
import {common} from '../models';
import {filetools} from '../models';
import {network} from '../models';
import {devtools} from '../models';
import {daily} from '../models';
import {screenshot} from '../models';
import {browser} from '../models';
import {scheduler} from '../models';
import {security} from '../models';
import {system} from '../models';
import {software} from '../models';
import {process} from '../models';
import {upload} from '../models';

export function AddCleanupTask(arg1:optimize.CleanupTask):Promise<void>;

export function AddClipboardItem(arg1:string,arg2:string):Promise<common.APIResponse>;

export function AddToPathVariable(arg1:string,arg2:string):Promise<void>;

export function AddWatermarkToImages(arg1:Array<string>,arg2:string,arg3:string,arg4:number):Promise<Array<filetools.WatermarkResult>>;

export function AnalyzeFolderSizes(arg1:string,arg2:number):Promise<Array<filetools.FolderSize>>;

export function AnalyzeServiceImpact(arg1:string):Promise<Array<string>>;

export function ApplyOptimizationProfile(arg1:string):Promise<Array<optimize.ChangeResult>>;

export function Base32ToHex(arg1:string):Promise<string>;

export function BatchCompressImages(arg1:string,arg2:number,arg3:string,arg4:number):Promise<Array<filetools.BatchCompressResult>>;

export function BatchKillProcesses(arg1:Array<number>):Promise<common.APIResponse>;

export function BatchPing(arg1:string,arg2:number):Promise<Array<network.BatchPingResult>>;

export function BatchUninstallSoftware(arg1:Array<string>):Promise<common.APIResponse>;

export function BeautifyCSS(arg1:string):Promise<devtools.CodeBeautifyResult>;

export function BeautifyHTML(arg1:string):Promise<devtools.CodeBeautifyResult>;

export function BeautifySQL(arg1:string):Promise<devtools.CodeBeautifyResult>;

export function BlockPort(arg1:number,arg2:string,arg3:string):Promise<void>;

export function BlockProgram(arg1:string,arg2:string):Promise<void>;

export function Calculate(arg1:string):Promise<daily.CalcResult>;

export function CanDisableService(arg1:string):Promise<boolean>;

export function CaptureAllScreens():Promise<screenshot.CaptureResult>;

export function CaptureScreen(arg1:number):Promise<screenshot.CaptureResult>;

export function ChangeService(arg1:string,arg2:string):Promise<void>;

export function CheckContextMenu():Promise<optimize.ContextMenuStatus>;

export function CheckDiskErrors(arg1:string):Promise<Array<string>>;

export function CheckIPConflict(arg1:string):Promise<Array<string>>;

export function CheckToolExists(arg1:string):Promise<boolean>;

export function CheckUpdate(arg1:string):Promise<devtools.ReleaseInfo>;

export function CleanBrowserData(arg1:Array<browser.CleanItem>):Promise<Array<browser.CleanResult>>;

export function CleanTargets(arg1:Array<string>):Promise<Array<optimize.CleanResult>>;

export function ClearClipboardHistory():Promise<common.APIResponse>;

export function ClearFolderMonitorEvents():Promise<void>;

export function ClearOperationLogs():Promise<common.APIResponse>;

export function ClearPerfHistory():Promise<void>;

export function ClearRecentDocs():Promise<void>;

export function ClearServiceBackups():Promise<void>;

export function ComputeFileHash(arg1:string,arg2:string):Promise<string>;

export function ConvertColor(arg1:string):Promise<devtools.ColorResult>;

export function ConvertCurrency(arg1:number,arg2:string,arg3:string):Promise<daily.ExchangeRate>;

export function ConvertEncoding(arg1:string,arg2:string,arg3:string):Promise<filetools.EncodingResult>;

export function ConvertImage(arg1:string,arg2:string):Promise<filetools.ConvertResult>;

export function ConvertTimestamp(arg1:number,arg2:string):Promise<devtools.TimestampResult>;

export function ConvertToPDF(arg1:string):Promise<string>;

export function CreateRestorePoint(arg1:string):Promise<void>;

export function CreateScheduledTask(arg1:string,arg2:number,arg3:number):Promise<scheduler.TaskInfo>;

export function DNSLookup(arg1:string):Promise<network.DNSResult>;

export function DateToTimestamp(arg1:string):Promise<devtools.TimestampConvert>;

export function DecodeBase64(arg1:string):Promise<devtools.CodecResult>;

export function DecodeJWT(arg1:string):Promise<devtools.JWTResult>;

export function DecodeURL(arg1:string):Promise<devtools.CodecResult>;

export function DecryptFile(arg1:string,arg2:string):Promise<security.EncryptResult>;

export function DeleteCleanupTask(arg1:string):Promise<void>;

export function DeleteEnvironmentVariable(arg1:string,arg2:string):Promise<void>;

export function DeleteFirewallRule(arg1:string):Promise<void>;

export function DeleteScheduledTask(arg1:string):Promise<boolean>;

export function DeleteStartupProgram(arg1:string,arg2:string):Promise<void>;

export function DetectBrowsers():Promise<Array<browser.Browser>>;

export function DiagnoseNetwork():Promise<Array<network.FixResult>>;

export function DiffFiles(arg1:string,arg2:string):Promise<Array<filetools.DiffLine>>;

export function DiffText(arg1:string,arg2:string):Promise<Array<devtools.DiffResult>>;

export function DisableBrowserExtension(arg1:string,arg2:string):Promise<common.APIResponse>;

export function EnableBrowserExtension(arg1:string,arg2:string):Promise<common.APIResponse>;

export function EncodeBase64(arg1:string):Promise<devtools.CodecResult>;

export function EncodeURL(arg1:string):Promise<devtools.CodecResult>;

export function EncryptFile(arg1:string,arg2:string):Promise<security.EncryptResult>;

export function ExportSoftwareList(arg1:string,arg2:string):Promise<common.APIResponse>;

export function FindDuplicateFiles(arg1:string,arg2:string):Promise<Array<filetools.DuplicateGroup>>;

export function FindLargeFiles(arg1:string,arg2:number,arg3:number):Promise<Array<filetools.LargeFile>>;

export function FixAllNetwork():Promise<Array<network.FixResult>>;

export function FixRegistryItems(arg1:Array<optimize.RegistryScanResult>):Promise<Array<optimize.RegistryFixResult>>;

export function FlushDNSCache():Promise<network.FixResult>;

export function FormatJSON(arg1:string):Promise<devtools.JSONResult>;

export function FormatTOML(arg1:string):Promise<devtools.FormatResult>;

export function FormatYAML(arg1:string):Promise<devtools.FormatResult>;

export function GeneratePassword(arg1:number,arg2:boolean,arg3:boolean,arg4:boolean,arg5:boolean):Promise<security.PasswordResult>;

export function GenerateQRCode(arg1:string,arg2:number):Promise<devtools.QRResult>;

export function GenerateSystemReport(arg1:string):Promise<string>;

export function GenerateUUID():Promise<string>;

export function GenerateUUIDs(arg1:number,arg2:number):Promise<devtools.UUIDGenResult>;

export function GetActivationInfo():Promise<system.ActivationInfo>;

export function GetActivationTools():Promise<Array<system.ActivationTool>>;

export function GetAllNetConnections():Promise<Array<network.NetConnection>>;

export function GetAllStartupPrograms():Promise<Array<optimize.StartupProgram>|optimize.StartupGroup>;

export function GetAppVersion():Promise<string>;

export function GetBatteryInfo():Promise<Array<system.BatteryInfo>>;

export function GetBrowserExtensions():Promise<Array<system.BrowserExtension>>;

export function GetBuildDate():Promise<string>;

export function GetCleanupLogs(arg1:number):Promise<Array<optimize.CleanupLog>>;

export function GetCleanupStats():Promise<Record<string, any>>;

export function GetCleanupTasks():Promise<Array<optimize.CleanupTask>>;

export function GetClipboardAndTranslate(arg1:string):Promise<daily.TranslateResult>;

export function GetClipboardHistory():Promise<common.APIResponse>;

export function GetClipboardText():Promise<string>;

export function GetConfig():Promise<common.AppConfig>;

export function GetDiskHealthInfo():Promise<Array<optimize.DiskHealthInfo>>;

export function GetDiskSpaceInfo():Promise<Array<Record<string, any>>>;

export function GetEnvironmentVariables(arg1:string):Promise<Array<optimize.EnvVar>>;

export function GetEstablishedConnections():Promise<Array<network.NetConnection>>;

export function GetExchangeRate(arg1:string,arg2:string):Promise<number>;

export function GetExternalTools():Promise<common.APIResponse>;

export function GetFileAssociations():Promise<Array<optimize.FileAssociation>>;

export function GetFirewallRules(arg1:string):Promise<Array<security.FirewallRule>>;

export function GetFirewallStatus():Promise<Record<string, boolean>>;

export function GetFolderMonitorEvents():Promise<Array<filetools.FolderChangeEvent>>;

export function GetHardwareMonitor():Promise<system.HardwareMonitor>;

export function GetHostsEntries():Promise<Array<optimize.HostsEntry>>;

export function GetInstalledSoftware():Promise<Array<software.SoftwareInfo>>;

export function GetKMSMethods():Promise<Array<system.KMSMethod>>;

export function GetListeningConnections():Promise<Array<network.NetConnection>>;

export function GetNetConnectionStats():Promise<Record<string, number>>;

export function GetNetworkConnections():Promise<Array<network.ConnectionInfo>>;

export function GetNowTimestamp():Promise<devtools.TimestampConvert>;

export function GetOpenWithList(arg1:string):Promise<Array<string>>;

export function GetOperationLogs():Promise<common.APIResponse>;

export function GetOptimizationProfiles():Promise<Array<optimize.OptimizationProfile>>;

export function GetPathVariable(arg1:string):Promise<Array<string>>;

export function GetPendingUpdates():Promise<Array<optimize.UpdateInfo>>;

export function GetPerfHistory():Promise<Array<system.PerfSnapshot>>;

export function GetPerfSnapshot():Promise<system.PerfSnapshot>;

export function GetPowerPlans():Promise<Array<system.PowerPlan>>;

export function GetProcessList():Promise<Array<process.ProcessInfo>>;

export function GetRestorePoints():Promise<Array<optimize.RestorePointInfo>>;

export function GetServiceBackups():Promise<Array<optimize.ServiceBackup>>;

export function GetServiceDependencyGraph():Promise<optimize.ServiceDependencyGraph>;

export function GetServices():Promise<Array<optimize.ServiceInfo>>;

export function GetShortcutKeys():Promise<Array<system.ShortcutKey>>;

export function GetStartupItemDelay(arg1:string):Promise<number>;

export function GetStartupItems():Promise<Array<optimize.StartupItem>>;

export function GetSupportedCurrencies():Promise<Array<daily.CurrencyInfo>>;

export function GetSystemInfo():Promise<system.SystemInfo>;

export function GetTemperatures():Promise<Array<system.TemperatureInfo>>;

export function GetToolsDir():Promise<string>;

export function GetTrafficSamples(arg1:number):Promise<Array<network.TrafficSample>>;

export function GetWiFiPasswords():Promise<Array<network.WiFiProfile>>;

export function GetWindowsUpdates():Promise<Array<optimize.UpdateInfo>>;

export function HSLToColor(arg1:number,arg2:number,arg3:number):Promise<devtools.ColorConvert>;

export function HasBattery():Promise<boolean>;

export function HexToBase32(arg1:string):Promise<string>;

export function HexToColor(arg1:string):Promise<devtools.ColorConvert>;

export function InstallContextMenu():Promise<optimize.ContextMenuStatus>;

export function InstallContextMenuDir():Promise<optimize.ContextMenuStatus>;

export function IsFolderMonitoring():Promise<boolean>;

export function IsRecording():Promise<boolean>;

export function KillNetConnection(arg1:number):Promise<void>;

export function KillProcess(arg1:number):Promise<void>;

export function LaunchMSTSC(arg1:string,arg2:string,arg3:number):Promise<void>;

export function ListScheduledTasks():Promise<Array<scheduler.TaskInfo>>;

export function MenuQuit():Promise<void>;

export function MenuShowApp():Promise<void>;

export function MinifyJSON(arg1:string):Promise<devtools.JSONResult>;

export function OpenDirectory(arg1:string):Promise<void>;

export function OpenExternalURL(arg1:string):Promise<void>;

export function OpenInExplorer(arg1:string):Promise<void>;

export function OptimizeDrive(arg1:string):Promise<void>;

export function Ping(arg1:string,arg2:number,arg3:number):Promise<network.PingSummary>;

export function PortScan(arg1:string,arg2:string):Promise<Array<network.PortResult>>;

export function PreviewFile(arg1:string):Promise<filetools.FilePreviewResult>;

export function QueryGeoIP(arg1:string):Promise<network.GeoIPResult>;

export function RGBToColor(arg1:number,arg2:number,arg3:number):Promise<devtools.ColorConvert>;

export function ReadClipboardImage():Promise<common.APIResponse>;

export function ReadFileAsBase64(arg1:string):Promise<string>;

export function ReleaseIP():Promise<network.FixResult>;

export function RemoveBrowserExtension(arg1:string,arg2:string):Promise<common.APIResponse>;

export function RemoveClipboardItem(arg1:number):Promise<common.APIResponse>;

export function RemoveFileAssociation(arg1:string):Promise<void>;

export function RemoveFromPathVariable(arg1:string,arg2:string):Promise<void>;

export function RenewIP():Promise<network.FixResult>;

export function ResetArpCache():Promise<network.FixResult>;

export function ResetProxy():Promise<network.FixResult>;

export function ResetTCPIP():Promise<network.FixResult>;

export function ResetWinsock():Promise<network.FixResult>;

export function RestoreService(arg1:string):Promise<void>;

export function RunCleanupTask(arg1:string):Promise<optimize.CleanupLog>;

export function RunExternalTool(arg1:string):Promise<common.APIResponse>;

export function RunHealthCheck():Promise<optimize.HealthReport>;

export function SaveClipboardImage(arg1:string):Promise<common.APIResponse>;

export function SaveConfig(arg1:common.AppConfig):Promise<void>;

export function SaveHostsEntries(arg1:Array<optimize.HostsEntry>):Promise<void>;

export function ScanBrowserData():Promise<Array<browser.CleanItem>>;

export function ScanCleanupPaths():Promise<Array<optimize.CleanupTarget>>;

export function ScanDiskTree(arg1:string,arg2:number):Promise<filetools.DiskTreeNode>;

export function ScanLAN():Promise<Array<network.LANDevice>>;

export function ScanRegistry():Promise<Array<optimize.RegistryScanResult>>;

export function ScanWiFiSignal():Promise<Array<network.SignalInfo>>;

export function SearchAndReplace(arg1:string,arg2:string,arg3:string,arg4:string):Promise<Array<filetools.ReplaceResult>>;

export function SearchFileContent(arg1:string,arg2:string,arg3:string):Promise<Array<filetools.SearchResult>>;

export function SearchNetConnections(arg1:string):Promise<Array<network.NetConnection>>;

export function SearchStartupPrograms(arg1:string):Promise<Array<optimize.StartupProgram>>;

export function SelectDirectory():Promise<string>;

export function SelectFile():Promise<string>;

export function SendHTTPRequest(arg1:devtools.HTTPRequest):Promise<devtools.HTTPResponse>;

export function SetEnvironmentVariable(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SetFileAssociation(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SetPowerPlan(arg1:string):Promise<void>;

export function SetProcessPriority(arg1:number,arg2:string):Promise<common.APIResponse>;

export function SetStartupItemDelay(arg1:string,arg2:number):Promise<common.APIResponse>;

export function ShredDir(arg1:string,arg2:number):Promise<Array<security.ShredResult>>;

export function ShredFile(arg1:string,arg2:number):Promise<security.ShredResult>;

export function StartFolderMonitor(arg1:string):Promise<void>;

export function StartScreenRecording(arg1:number,arg2:number,arg3:boolean):Promise<daily.ScreenRecordResult>;

export function StopFolderMonitor():Promise<void>;

export function StopScreenRecording():Promise<daily.ScreenRecordResult>;

export function TestRegex(arg1:string,arg2:string):Promise<devtools.RegexTestResult>;

export function TimestampToDate(arg1:number):Promise<devtools.TimestampConvert>;

export function ToggleCleanupTask(arg1:string,arg2:boolean):Promise<void>;

export function ToggleFirewallRule(arg1:string,arg2:boolean):Promise<void>;

export function ToggleStartupItem(arg1:string,arg2:boolean):Promise<void>;

export function ToggleStartupProgram(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function Translate(arg1:string,arg2:string,arg3:string):Promise<daily.TranslateResult>;

export function UninstallContextMenu():Promise<optimize.ContextMenuStatus>;

export function UninstallSoftware(arg1:string):Promise<common.APIResponse>;

export function UpdateCleanupTask(arg1:optimize.CleanupTask):Promise<void>;

export function UploadFileToServer(arg1:string,arg2:string,arg3:string,arg4:string):Promise<upload.UploadResult>;
