// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddClipboardItem(arg1, arg2) {
  return window['go']['main']['App']['AddClipboardItem'](arg1, arg2);
}

export function AnalyzeFolderSizes(arg1, arg2) {
  return window['go']['main']['App']['AnalyzeFolderSizes'](arg1, arg2);
}

export function ApplyOptimizationProfile(arg1) {
  return window['go']['main']['App']['ApplyOptimizationProfile'](arg1);
}

export function BatchCompressImages(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['BatchCompressImages'](arg1, arg2, arg3, arg4);
}

export function BatchKillProcesses(arg1) {
  return window['go']['main']['App']['BatchKillProcesses'](arg1);
}

export function BatchPing(arg1, arg2) {
  return window['go']['main']['App']['BatchPing'](arg1, arg2);
}

export function BatchRename(arg1, arg2) {
  return window['go']['main']['App']['BatchRename'](arg1, arg2);
}

export function BatchRenamePreview(arg1, arg2) {
  return window['go']['main']['App']['BatchRenamePreview'](arg1, arg2);
}

export function BatchUninstallSoftware(arg1) {
  return window['go']['main']['App']['BatchUninstallSoftware'](arg1);
}

export function BeautifyCSS(arg1) {
  return window['go']['main']['App']['BeautifyCSS'](arg1);
}

export function BeautifyHTML(arg1) {
  return window['go']['main']['App']['BeautifyHTML'](arg1);
}

export function BeautifySQL(arg1) {
  return window['go']['main']['App']['BeautifySQL'](arg1);
}

export function CaptureAllScreens() {
  return window['go']['main']['App']['CaptureAllScreens']();
}

export function CaptureScreen(arg1) {
  return window['go']['main']['App']['CaptureScreen'](arg1);
}

export function ChangeService(arg1, arg2) {
  return window['go']['main']['App']['ChangeService'](arg1, arg2);
}

export function CheckContextMenu() {
  return window['go']['main']['App']['CheckContextMenu']();
}

export function CheckIPConflict(arg1) {
  return window['go']['main']['App']['CheckIPConflict'](arg1);
}

export function CheckToolExists(arg1) {
  return window['go']['main']['App']['CheckToolExists'](arg1);
}

export function CheckUpdate(arg1) {
  return window['go']['main']['App']['CheckUpdate'](arg1);
}

export function CleanBrowserData(arg1) {
  return window['go']['main']['App']['CleanBrowserData'](arg1);
}

export function CleanTargets(arg1) {
  return window['go']['main']['App']['CleanTargets'](arg1);
}

export function ClearClipboardHistory() {
  return window['go']['main']['App']['ClearClipboardHistory']();
}

export function ClearOperationLogs() {
  return window['go']['main']['App']['ClearOperationLogs']();
}

export function ClearRecentDocs() {
  return window['go']['main']['App']['ClearRecentDocs']();
}

export function ClearServiceBackups() {
  return window['go']['main']['App']['ClearServiceBackups']();
}

export function ComputeFileHash(arg1, arg2) {
  return window['go']['main']['App']['ComputeFileHash'](arg1, arg2);
}

export function ConvertColor(arg1) {
  return window['go']['main']['App']['ConvertColor'](arg1);
}

export function ConvertEncoding(arg1, arg2, arg3) {
  return window['go']['main']['App']['ConvertEncoding'](arg1, arg2, arg3);
}

export function ConvertImage(arg1, arg2) {
  return window['go']['main']['App']['ConvertImage'](arg1, arg2);
}

export function ConvertTimestamp(arg1, arg2) {
  return window['go']['main']['App']['ConvertTimestamp'](arg1, arg2);
}

export function ConvertToPDF(arg1) {
  return window['go']['main']['App']['ConvertToPDF'](arg1);
}

export function CreateRestorePoint(arg1) {
  return window['go']['main']['App']['CreateRestorePoint'](arg1);
}

export function CreateScheduledTask(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateScheduledTask'](arg1, arg2, arg3);
}

export function DNSLookup(arg1) {
  return window['go']['main']['App']['DNSLookup'](arg1);
}

export function DecodeBase64(arg1) {
  return window['go']['main']['App']['DecodeBase64'](arg1);
}

export function DecodeJWT(arg1) {
  return window['go']['main']['App']['DecodeJWT'](arg1);
}

export function DecodeURL(arg1) {
  return window['go']['main']['App']['DecodeURL'](arg1);
}

export function DecryptFile(arg1, arg2) {
  return window['go']['main']['App']['DecryptFile'](arg1, arg2);
}

export function DeleteScheduledTask(arg1) {
  return window['go']['main']['App']['DeleteScheduledTask'](arg1);
}

export function DetectBrowsers() {
  return window['go']['main']['App']['DetectBrowsers']();
}

export function DiagnoseNetwork() {
  return window['go']['main']['App']['DiagnoseNetwork']();
}

export function DiffFiles(arg1, arg2) {
  return window['go']['main']['App']['DiffFiles'](arg1, arg2);
}

export function DiffText(arg1, arg2) {
  return window['go']['main']['App']['DiffText'](arg1, arg2);
}

export function DisableBrowserExtension(arg1, arg2) {
  return window['go']['main']['App']['DisableBrowserExtension'](arg1, arg2);
}

export function EmptyRecycleBin() {
  return window['go']['main']['App']['EmptyRecycleBin']();
}

export function EnableBrowserExtension(arg1, arg2) {
  return window['go']['main']['App']['EnableBrowserExtension'](arg1, arg2);
}

export function EncodeBase64(arg1) {
  return window['go']['main']['App']['EncodeBase64'](arg1);
}

export function EncodeURL(arg1) {
  return window['go']['main']['App']['EncodeURL'](arg1);
}

export function EncryptFile(arg1, arg2) {
  return window['go']['main']['App']['EncryptFile'](arg1, arg2);
}

export function ExecuteOrganize(arg1, arg2) {
  return window['go']['main']['App']['ExecuteOrganize'](arg1, arg2);
}

export function ExportSoftwareList(arg1, arg2) {
  return window['go']['main']['App']['ExportSoftwareList'](arg1, arg2);
}

export function FindDuplicateFiles(arg1, arg2) {
  return window['go']['main']['App']['FindDuplicateFiles'](arg1, arg2);
}

export function FindLargeFiles(arg1, arg2, arg3) {
  return window['go']['main']['App']['FindLargeFiles'](arg1, arg2, arg3);
}

export function FixAllNetwork() {
  return window['go']['main']['App']['FixAllNetwork']();
}

export function FlushDNSCache() {
  return window['go']['main']['App']['FlushDNSCache']();
}

export function FormatJSON(arg1) {
  return window['go']['main']['App']['FormatJSON'](arg1);
}

export function FormatTOML(arg1) {
  return window['go']['main']['App']['FormatTOML'](arg1);
}

export function FormatYAML(arg1) {
  return window['go']['main']['App']['FormatYAML'](arg1);
}

export function GeneratePassword(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['GeneratePassword'](arg1, arg2, arg3, arg4, arg5);
}

export function GenerateQRCode(arg1, arg2) {
  return window['go']['main']['App']['GenerateQRCode'](arg1, arg2);
}

export function GenerateSystemReport(arg1) {
  return window['go']['main']['App']['GenerateSystemReport'](arg1);
}

export function GenerateUUID() {
  return window['go']['main']['App']['GenerateUUID']();
}

export function GenerateUUIDs(arg1, arg2) {
  return window['go']['main']['App']['GenerateUUIDs'](arg1, arg2);
}

export function GetActivationInfo() {
  return window['go']['main']['App']['GetActivationInfo']();
}

export function GetActivationTools() {
  return window['go']['main']['App']['GetActivationTools']();
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetBrowserExtensions() {
  return window['go']['main']['App']['GetBrowserExtensions']();
}

export function GetBuildDate() {
  return window['go']['main']['App']['GetBuildDate']();
}

export function GetClipboardHistory() {
  return window['go']['main']['App']['GetClipboardHistory']();
}

export function GetClipboardText() {
  return window['go']['main']['App']['GetClipboardText']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetExternalTools() {
  return window['go']['main']['App']['GetExternalTools']();
}

export function GetHardwareMonitor() {
  return window['go']['main']['App']['GetHardwareMonitor']();
}

export function GetHostsEntries() {
  return window['go']['main']['App']['GetHostsEntries']();
}

export function GetInstalledSoftware() {
  return window['go']['main']['App']['GetInstalledSoftware']();
}

export function GetKMSMethods() {
  return window['go']['main']['App']['GetKMSMethods']();
}

export function GetNetworkConnections() {
  return window['go']['main']['App']['GetNetworkConnections']();
}

export function GetOperationLogs() {
  return window['go']['main']['App']['GetOperationLogs']();
}

export function GetOptimizationProfiles() {
  return window['go']['main']['App']['GetOptimizationProfiles']();
}

export function GetPendingUpdates() {
  return window['go']['main']['App']['GetPendingUpdates']();
}

export function GetPowerPlans() {
  return window['go']['main']['App']['GetPowerPlans']();
}

export function GetProcessList() {
  return window['go']['main']['App']['GetProcessList']();
}

export function GetRecycleBinInfo() {
  return window['go']['main']['App']['GetRecycleBinInfo']();
}

export function GetRestorePoints() {
  return window['go']['main']['App']['GetRestorePoints']();
}

export function GetServiceBackups() {
  return window['go']['main']['App']['GetServiceBackups']();
}

export function GetServices() {
  return window['go']['main']['App']['GetServices']();
}

export function GetShortcutKeys() {
  return window['go']['main']['App']['GetShortcutKeys']();
}

export function GetStartupItemDelay(arg1) {
  return window['go']['main']['App']['GetStartupItemDelay'](arg1);
}

export function GetStartupItems() {
  return window['go']['main']['App']['GetStartupItems']();
}

export function GetSystemInfo() {
  return window['go']['main']['App']['GetSystemInfo']();
}

export function GetTemperatures() {
  return window['go']['main']['App']['GetTemperatures']();
}

export function GetToolsDir() {
  return window['go']['main']['App']['GetToolsDir']();
}

export function GetTrafficSamples(arg1) {
  return window['go']['main']['App']['GetTrafficSamples'](arg1);
}

export function GetWiFiPasswords() {
  return window['go']['main']['App']['GetWiFiPasswords']();
}

export function GetWindowsUpdates() {
  return window['go']['main']['App']['GetWindowsUpdates']();
}

export function InstallContextMenu() {
  return window['go']['main']['App']['InstallContextMenu']();
}

export function InstallContextMenuDir() {
  return window['go']['main']['App']['InstallContextMenuDir']();
}

export function KillProcess(arg1) {
  return window['go']['main']['App']['KillProcess'](arg1);
}

export function LaunchMSTSC(arg1, arg2, arg3) {
  return window['go']['main']['App']['LaunchMSTSC'](arg1, arg2, arg3);
}

export function ListScheduledTasks() {
  return window['go']['main']['App']['ListScheduledTasks']();
}

export function MenuQuit() {
  return window['go']['main']['App']['MenuQuit']();
}

export function MenuShowApp() {
  return window['go']['main']['App']['MenuShowApp']();
}

export function MinifyJSON(arg1) {
  return window['go']['main']['App']['MinifyJSON'](arg1);
}

export function OpenExternalURL(arg1) {
  return window['go']['main']['App']['OpenExternalURL'](arg1);
}

export function OpenInExplorer(arg1) {
  return window['go']['main']['App']['OpenInExplorer'](arg1);
}

export function Ping(arg1, arg2, arg3) {
  return window['go']['main']['App']['Ping'](arg1, arg2, arg3);
}

export function PortScan(arg1, arg2) {
  return window['go']['main']['App']['PortScan'](arg1, arg2);
}

export function PreviewFile(arg1) {
  return window['go']['main']['App']['PreviewFile'](arg1);
}

export function PreviewOrganize(arg1, arg2) {
  return window['go']['main']['App']['PreviewOrganize'](arg1, arg2);
}

export function QueryGeoIP(arg1) {
  return window['go']['main']['App']['QueryGeoIP'](arg1);
}

export function ReadClipboardImage() {
  return window['go']['main']['App']['ReadClipboardImage']();
}

export function ReadFileAsBase64(arg1) {
  return window['go']['main']['App']['ReadFileAsBase64'](arg1);
}

export function ReleaseIP() {
  return window['go']['main']['App']['ReleaseIP']();
}

export function RemoveBrowserExtension(arg1, arg2) {
  return window['go']['main']['App']['RemoveBrowserExtension'](arg1, arg2);
}

export function RemoveClipboardItem(arg1) {
  return window['go']['main']['App']['RemoveClipboardItem'](arg1);
}

export function RenewIP() {
  return window['go']['main']['App']['RenewIP']();
}

export function ResetArpCache() {
  return window['go']['main']['App']['ResetArpCache']();
}

export function ResetProxy() {
  return window['go']['main']['App']['ResetProxy']();
}

export function ResetTCPIP() {
  return window['go']['main']['App']['ResetTCPIP']();
}

export function ResetWinsock() {
  return window['go']['main']['App']['ResetWinsock']();
}

export function RestoreService(arg1) {
  return window['go']['main']['App']['RestoreService'](arg1);
}

export function RunExternalTool(arg1) {
  return window['go']['main']['App']['RunExternalTool'](arg1);
}

export function RunHealthCheck() {
  return window['go']['main']['App']['RunHealthCheck']();
}

export function SaveClipboardImage(arg1) {
  return window['go']['main']['App']['SaveClipboardImage'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SaveHostsEntries(arg1) {
  return window['go']['main']['App']['SaveHostsEntries'](arg1);
}

export function ScanBrowserData() {
  return window['go']['main']['App']['ScanBrowserData']();
}

export function ScanCleanupPaths() {
  return window['go']['main']['App']['ScanCleanupPaths']();
}

export function ScanLAN() {
  return window['go']['main']['App']['ScanLAN']();
}

export function ScanRegistry() {
  return window['go']['main']['App']['ScanRegistry']();
}

export function ScanWiFiSignal() {
  return window['go']['main']['App']['ScanWiFiSignal']();
}

export function SearchAndReplace(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SearchAndReplace'](arg1, arg2, arg3, arg4);
}

export function SearchFileContent(arg1, arg2, arg3) {
  return window['go']['main']['App']['SearchFileContent'](arg1, arg2, arg3);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SelectFile() {
  return window['go']['main']['App']['SelectFile']();
}

export function SendHTTPRequest(arg1) {
  return window['go']['main']['App']['SendHTTPRequest'](arg1);
}

export function SetPowerPlan(arg1) {
  return window['go']['main']['App']['SetPowerPlan'](arg1);
}

export function SetProcessPriority(arg1, arg2) {
  return window['go']['main']['App']['SetProcessPriority'](arg1, arg2);
}

export function SetStartupItemDelay(arg1, arg2) {
  return window['go']['main']['App']['SetStartupItemDelay'](arg1, arg2);
}

export function ShredDir(arg1, arg2) {
  return window['go']['main']['App']['ShredDir'](arg1, arg2);
}

export function ShredFile(arg1, arg2) {
  return window['go']['main']['App']['ShredFile'](arg1, arg2);
}

export function TestRegex(arg1, arg2) {
  return window['go']['main']['App']['TestRegex'](arg1, arg2);
}

export function ToggleStartupItem(arg1, arg2) {
  return window['go']['main']['App']['ToggleStartupItem'](arg1, arg2);
}

export function UninstallContextMenu() {
  return window['go']['main']['App']['UninstallContextMenu']();
}

export function UninstallSoftware(arg1) {
  return window['go']['main']['App']['UninstallSoftware'](arg1);
}

export function UploadFileToServer(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UploadFileToServer'](arg1, arg2, arg3, arg4);
}
