// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {common} from '../models';
import {filetools} from '../models';
import {optimize} from '../models';
import {network} from '../models';
import {devtools} from '../models';
import {screenshot} from '../models';
import {browser} from '../models';
import {scheduler} from '../models';
import {security} from '../models';
import {system} from '../models';
import {software} from '../models';
import {process} from '../models';
import {upload} from '../models';

export function AddClipboardItem(arg1:string,arg2:string):Promise<common.APIResponse>;

export function AnalyzeFolderSizes(arg1:string,arg2:number):Promise<Array<filetools.FolderSize>>;

export function ApplyOptimizationProfile(arg1:string):Promise<Array<optimize.ChangeResult>>;

export function BatchCompressImages(arg1:string,arg2:number,arg3:string,arg4:number):Promise<Array<filetools.BatchCompressResult>>;

export function BatchKillProcesses(arg1:Array<number>):Promise<common.APIResponse>;

export function BatchPing(arg1:string,arg2:number):Promise<Array<network.BatchPingResult>>;

export function BatchRename(arg1:string,arg2:filetools.RenameRule):Promise<Array<filetools.RenamePreview>>;

export function BatchRenamePreview(arg1:string,arg2:filetools.RenameRule):Promise<Array<filetools.RenamePreview>>;

export function BatchUninstallSoftware(arg1:Array<string>):Promise<common.APIResponse>;

export function BeautifyCSS(arg1:string):Promise<devtools.CodeBeautifyResult>;

export function BeautifyHTML(arg1:string):Promise<devtools.CodeBeautifyResult>;

export function BeautifySQL(arg1:string):Promise<devtools.CodeBeautifyResult>;

export function CaptureAllScreens():Promise<screenshot.CaptureResult>;

export function CaptureScreen(arg1:number):Promise<screenshot.CaptureResult>;

export function ChangeService(arg1:string,arg2:string):Promise<void>;

export function CheckContextMenu():Promise<optimize.ContextMenuStatus>;

export function CheckIPConflict(arg1:string):Promise<Array<string>>;

export function CheckToolExists(arg1:string):Promise<boolean>;

export function CheckUpdate(arg1:string):Promise<devtools.ReleaseInfo>;

export function CleanBrowserData(arg1:Array<browser.CleanItem>):Promise<Array<browser.CleanResult>>;

export function CleanTargets(arg1:Array<string>):Promise<Array<optimize.CleanResult>>;

export function ClearClipboardHistory():Promise<common.APIResponse>;

export function ClearOperationLogs():Promise<common.APIResponse>;

export function ClearRecentDocs():Promise<void>;

export function ClearServiceBackups():Promise<void>;

export function ComputeFileHash(arg1:string,arg2:string):Promise<string>;

export function ConvertColor(arg1:string):Promise<devtools.ColorResult>;

export function ConvertEncoding(arg1:string,arg2:string,arg3:string):Promise<filetools.EncodingResult>;

export function ConvertImage(arg1:string,arg2:string):Promise<filetools.ConvertResult>;

export function ConvertTimestamp(arg1:number,arg2:string):Promise<devtools.TimestampResult>;

export function ConvertToPDF(arg1:string):Promise<filetools.DocConvertResult>;

export function CreateRestorePoint(arg1:string):Promise<void>;

export function CreateScheduledTask(arg1:string,arg2:number,arg3:number):Promise<scheduler.TaskInfo>;

export function DNSLookup(arg1:string):Promise<network.DNSResult>;

export function DecodeBase64(arg1:string):Promise<devtools.CodecResult>;

export function DecodeJWT(arg1:string):Promise<devtools.JWTResult>;

export function DecodeURL(arg1:string):Promise<devtools.CodecResult>;

export function DecryptFile(arg1:string,arg2:string):Promise<security.EncryptResult>;

export function DeleteScheduledTask(arg1:string):Promise<boolean>;

export function DetectBrowsers():Promise<Array<browser.Browser>>;

export function DiagnoseNetwork():Promise<Array<network.FixResult>>;

export function DiffFiles(arg1:string,arg2:string):Promise<Array<filetools.DiffLine>>;

export function DiffText(arg1:string,arg2:string):Promise<Array<devtools.DiffResult>>;

export function DisableBrowserExtension(arg1:string,arg2:string):Promise<common.APIResponse>;

export function EmptyRecycleBin():Promise<void>;

export function EnableBrowserExtension(arg1:string,arg2:string):Promise<common.APIResponse>;

export function EncodeBase64(arg1:string):Promise<devtools.CodecResult>;

export function EncodeURL(arg1:string):Promise<devtools.CodecResult>;

export function EncryptFile(arg1:string,arg2:string):Promise<security.EncryptResult>;

export function ExecuteOrganize(arg1:string,arg2:filetools.OrganizeRule):Promise<Array<filetools.OrganizeResult>>;

export function ExportSoftwareList(arg1:string,arg2:string):Promise<common.APIResponse>;

export function FindDuplicateFiles(arg1:string,arg2:string):Promise<Array<filetools.DuplicateGroup>>;

export function FindLargeFiles(arg1:string,arg2:number,arg3:number):Promise<Array<filetools.LargeFile>>;

export function FixAllNetwork():Promise<Array<network.FixResult>>;

export function FlushDNSCache():Promise<network.FixResult>;

export function FormatJSON(arg1:string):Promise<devtools.JSONResult>;

export function FormatTOML(arg1:string):Promise<devtools.FormatResult>;

export function FormatYAML(arg1:string):Promise<devtools.FormatResult>;

export function GeneratePassword(arg1:number,arg2:boolean,arg3:boolean,arg4:boolean,arg5:boolean):Promise<security.PasswordResult>;

export function GenerateQRCode(arg1:string,arg2:number):Promise<devtools.QRResult>;

export function GenerateSystemReport(arg1:string):Promise<string>;

export function GenerateUUID():Promise<string>;

export function GenerateUUIDs(arg1:number,arg2:number):Promise<devtools.UUIDGenResult>;

export function GetActivationInfo():Promise<system.ActivationInfo>;

export function GetActivationTools():Promise<Array<system.ActivationTool>>;

export function GetAppVersion():Promise<string>;

export function GetBrowserExtensions():Promise<Array<system.BrowserExtension>>;

export function GetBuildDate():Promise<string>;

export function GetClipboardHistory():Promise<common.APIResponse>;

export function GetClipboardText():Promise<string>;

export function GetConfig():Promise<common.AppConfig>;

export function GetExternalTools():Promise<common.APIResponse>;

export function GetHardwareMonitor():Promise<system.HardwareMonitor>;

export function GetHostsEntries():Promise<Array<optimize.HostsEntry>>;

export function GetInstalledSoftware():Promise<Array<software.SoftwareInfo>>;

export function GetKMSMethods():Promise<Array<system.KMSMethod>>;

export function GetNetworkConnections():Promise<Array<network.ConnectionInfo>>;

export function GetOperationLogs():Promise<common.APIResponse>;

export function GetOptimizationProfiles():Promise<Array<optimize.OptimizationProfile>>;

export function GetPendingUpdates():Promise<Array<optimize.UpdateInfo>>;

export function GetPowerPlans():Promise<Array<system.PowerPlan>>;

export function GetProcessList():Promise<Array<process.ProcessInfo>>;

export function GetRecycleBinInfo():Promise<filetools.RecycleBinInfo>;

export function GetRestorePoints():Promise<Array<optimize.RestorePointInfo>>;

export function GetServiceBackups():Promise<Array<optimize.ServiceBackup>>;

export function GetServices():Promise<Array<optimize.ServiceInfo>>;

export function GetShortcutKeys():Promise<Array<system.ShortcutKey>>;

export function GetStartupItemDelay(arg1:string):Promise<number>;

export function GetStartupItems():Promise<Array<optimize.StartupItem>>;

export function GetSystemInfo():Promise<system.SystemInfo>;

export function GetTemperatures():Promise<Array<system.TemperatureInfo>>;

export function GetToolsDir():Promise<string>;

export function GetTrafficSamples(arg1:number):Promise<Array<network.TrafficSample>>;

export function GetWiFiPasswords():Promise<Array<network.WiFiProfile>>;

export function GetWindowsUpdates():Promise<Array<optimize.UpdateInfo>>;

export function InstallContextMenu():Promise<optimize.ContextMenuStatus>;

export function InstallContextMenuDir():Promise<optimize.ContextMenuStatus>;

export function KillProcess(arg1:number):Promise<void>;

export function LaunchMSTSC(arg1:string,arg2:string,arg3:number):Promise<void>;

export function ListScheduledTasks():Promise<Array<scheduler.TaskInfo>>;

export function MenuQuit():Promise<void>;

export function MenuShowApp():Promise<void>;

export function MinifyJSON(arg1:string):Promise<devtools.JSONResult>;

export function OpenExternalURL(arg1:string):Promise<void>;

export function OpenInExplorer(arg1:string):Promise<void>;

export function Ping(arg1:string,arg2:number,arg3:number):Promise<network.PingSummary>;

export function PortScan(arg1:string,arg2:string):Promise<Array<network.PortResult>>;

export function PreviewFile(arg1:string):Promise<filetools.FilePreviewResult>;

export function PreviewOrganize(arg1:string,arg2:filetools.OrganizeRule):Promise<Array<filetools.OrganizePreview>>;

export function QueryGeoIP(arg1:string):Promise<network.GeoIPResult>;

export function ReadClipboardImage():Promise<common.APIResponse>;

export function ReadFileAsBase64(arg1:string):Promise<string>;

export function ReleaseIP():Promise<network.FixResult>;

export function RemoveBrowserExtension(arg1:string,arg2:string):Promise<common.APIResponse>;

export function RemoveClipboardItem(arg1:number):Promise<common.APIResponse>;

export function RenewIP():Promise<network.FixResult>;

export function ResetArpCache():Promise<network.FixResult>;

export function ResetProxy():Promise<network.FixResult>;

export function ResetTCPIP():Promise<network.FixResult>;

export function ResetWinsock():Promise<network.FixResult>;

export function RestoreService(arg1:string):Promise<void>;

export function RunExternalTool(arg1:string):Promise<common.APIResponse>;

export function RunHealthCheck():Promise<optimize.HealthReport>;

export function SaveClipboardImage(arg1:string):Promise<common.APIResponse>;

export function SaveConfig(arg1:common.AppConfig):Promise<void>;

export function SaveHostsEntries(arg1:Array<optimize.HostsEntry>):Promise<void>;

export function ScanBrowserData():Promise<Array<browser.CleanItem>>;

export function ScanCleanupPaths():Promise<Array<optimize.CleanupTarget>>;

export function ScanLAN():Promise<Array<network.LANDevice>>;

export function ScanRegistry():Promise<Array<optimize.RegistryScanResult>>;

export function ScanWiFiSignal():Promise<Array<network.SignalInfo>>;

export function SearchAndReplace(arg1:string,arg2:string,arg3:string,arg4:string):Promise<Array<filetools.ReplaceResult>>;

export function SearchFileContent(arg1:string,arg2:string,arg3:string):Promise<Array<filetools.SearchResult>>;

export function SelectDirectory():Promise<string>;

export function SelectFile():Promise<string>;

export function SendHTTPRequest(arg1:devtools.HTTPRequest):Promise<devtools.HTTPResponse>;

export function SetPowerPlan(arg1:string):Promise<void>;

export function SetProcessPriority(arg1:number,arg2:string):Promise<common.APIResponse>;

export function SetStartupItemDelay(arg1:string,arg2:number):Promise<common.APIResponse>;

export function ShredDir(arg1:string,arg2:number):Promise<Array<security.ShredResult>>;

export function ShredFile(arg1:string,arg2:number):Promise<security.ShredResult>;

export function TestRegex(arg1:string,arg2:string):Promise<devtools.RegexTestResult>;

export function ToggleStartupItem(arg1:string,arg2:boolean):Promise<void>;

export function UninstallContextMenu():Promise<optimize.ContextMenuStatus>;

export function UninstallSoftware(arg1:string):Promise<common.APIResponse>;

export function UploadFileToServer(arg1:string,arg2:string,arg3:string,arg4:string):Promise<upload.UploadResult>;
